
MODEL:
    n_head: 10
    n_layer: 12
    dropout: 0.1
    d_inner: 4096        #d_ff
    d_embed: 1024
    d_model: 1024
    dropatt: 0.0         #attention probability dropout rate
    query_dim: 256 #16        #64
    seq_len: 1024         #512
    n_token: 392
    mem_len: 1024
    ext_len: 0
    tgt_len: 70
    eval_tgt_len: 50
    init: 'normal'       #parameter initializer to use.
    emb_init: 'normal'   #parameter initializer to use.
    init_range: 0.1
    emb_init_range: 0.01 #parameters initialized by U(-init_range, init_range)
    init_std: 0.02       #parameters initialized by N(0, init_std)
    proj_init_std: 0.01
    clamp_len: -1        #use the same pos embeddings after clamp_len
    div_val: 1
    position_concat: False
    pre_lnorm: True      #apply LayerNorm to the input instead of the output
    same_length: True    #use the same attn length for all tokens


TRAIN: 
    exp_tag: 'final_head10_layer12_emb1024_q256'
    ROOT: '../../../dataset/representations/uncond/remi/ailab17k_from-scratch_remi'
    midiDIR: '/home/atosystem/nas_disk/projects/multitrack/mydataset/midiFullPkls'
    selected_songs_json: './dataset/selected_songs_id_new.json'
    gpuID: '0'
    output_dir: "./exp"
    batch_size: 7  #5
    lr: 0.0002               
    num_epochs: 600
    save_freq: 1
    save_freq_step: 128
    seed: 2222
    optim: 'adam'    
    no_cuda: False
    resume_training_model: None
    dataloader_worker_num: 16
    seq_len: 1024
    group_size: 40
    # resume_training_model: '/home/atosystem/nas_disk/projects/multitrack/remi-xl_mmm/exp/20211225-122249/ep_10.pth.tar'
    # resume_training_model: '/volume/ai-music-wayne/aaai/from-scratch/remi-xl_review/result/20200901-064426/ep_170.pth.tar'


INFERENCE:
    num_sample: 10
    gpuID: '0'
    dictionary_path: '../../../dataset/representations/uncond/remi/ailab17k_from-scratch_remi/dictionary.pkl'
    experiment_dir: '/home/atosystem/nas_disk/projects/multitrack/remi-xl_remiMulti/exp/final_head10_layer12_emb1024_q256'
    generated_dir: './gen_midis_final_head10_layer12_emb1024_q256'
    checkpoint_type: epoch_idx    # best_train, best_val, epoch_idx
    model_epoch: 13
    no_cuda: False
